name: Get all latest stats SVG

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  user: SushankSharma
  template: classic
  config_timezone: Asia/Taipei

jobs:
  header:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: header.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ env.user }}
          template: ${{ env.template }}
          base: header
          config_timezone: ${{ env.config_timezone }}

  acti_comm:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: acti_comm.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ env.user }}
          template: ${{ env.template }}
          base: activity, community
          config_timezone: ${{ env.config_timezone }}

  iso_calender:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: iso_calender.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ env.user }}
          template: ${{ env.template }}
          base: ""
          config_timezone: ${{ env.config_timezone }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

  issue_pr_lang:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: issue_pr_lang.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ env.user }}
          template: ${{ env.template }}
          base: ""
          config_timezone: Asia/Taipei
          plugin_followup: yes
          plugin_languages: yes

  metadata:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metadata.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ env.user }}
          template: ${{ env.template }}
          base: metadata
          config_timezone: ${{ env.config_timezone }}

  repositories:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: repositories.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ env.user }}
          template: ${{ env.template }}
          base: repositories
          config_timezone: ${{ env.config_timezone }}

  snake_animation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        run: npx github-contributions-snake

      - name: Commit and Push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Add Snake Animation"
          git push
